### ISSUE TITLE
Possible Enchancements.

### ISSUE THREAD

**Issue by HexadecimalPython** [AlexFlipnote/GoogleRPC#2]
Not override the current discord status when nothing is playing which would allow for I to set it as a background task permanently on autoreboot incase of failure, Currently shows Paused when script is ran without GPMDP open. (May break the Paused status, could add a detection for gpmdp.exe)

Fix the reoccurring issues as stated below;
![image](https://user-images.githubusercontent.com/21255961/35139169-60f50558-fd0b-11e7-9eec-4178be264fb6.png)

**Comment by AlexFlipnote** [comment]
Will look into it

**Comment by AlexFlipnote** [comment]
Should be solved in f011868
